### ISSUE TITLE
GrammY runner plugin support for scaling up

### ISSUE THREAD

**Issue by chiliec** [bot-base/telegram-bot-template#445]
https://grammy.dev/advanced/scaling

**Comment by deptyped** [comment]
@grammyjs/runner is [supported](https://github.com/bot-base/telegram-bot-template?tab=readme-ov-file#grammy-runner-grammydevpluginsrunner). We have an example in the [example/plugin-runner](https://github.com/bot-base/telegram-bot-template/compare/example/plugin-runner) branch of how to use it instead of a webhook.

**Comment by chiliec** [comment]
Sorry, I didn't know that it is **instead** of webhooks, not together :)
